### PR TITLE
Replace circuits screenshot by animated gif demo

### PR DESCRIPTION
**Pull request by jvoigtlaender**

### CODE REVIEW

**Comment by joelclermont** [comment]
I think your gif might be corrupt. I've tried opening it in a couple image viewers and it won't load for me. Can you double check it?

**Comment by joelclermont** [comment]
Update: It loads in Chrome, but not in Safari or OS X Preview.

**Comment by jvoigtlaender** [comment]
It loads in Firefox and Chrome on Windows. It loads in several image viewers on Windows. It loads in iOS Safari...

I dont't think there is anything to fix. Maybe yor local OS X stuff is broken in some way?

**Comment by jvoigtlaender** [comment]
It also loads in Opera Mini and Chrome on iOS. And in Internet Explorer on Windows...

**Comment by joelclermont** [comment]
Ok I'll try it again when I get back. Thanks for double checking.

**Comment by joelclermont** [comment]
It has been merged and deployed. Oddly, on both of my Macs (OS X 10.11.6 and Safari 9.1.3) the gif does not play. Other gifs on the site do.

But I tested it using the same OS/Safari combo in Browserstack and it looks fine there. Thanks again!

**Comment by jvoigtlaender** [comment]
Thanks!

Strange about that specific OS X case.

FWIW, I just tried in two Linux VMs, and they both do play that gif in their browser.

**Pull request merged**
