### PR TITLE
Add pace.ninja with optimized image

### PR DESCRIPTION
**Pull request by JacobEvelyn**

### CODE REVIEW

**Comment by prikhi** [comment]
Thanks!

**Comment by JacobEvelyn** [comment]
Uh oh... did I break it?

screen shot 2017-10-06 at 9 08 31 am

**Comment by joelclermont** [comment]
Weird, repositoryUrl should be optional. I added it in with a null value just to fix it, but I'll dig into it later when I have more time. Site is back up

**Comment by joelclermont** [comment]
@JacobEvelyn So the value of repositoryUrl is optional, but the field being present is required.

https://github.com/elm-community/builtwithelm/blob/449664295b0e1ac884018bfe15524149d48285c7/src/Model.elm#L37

We could move the maybe outside the field to make it optional, but it's probably just as easy  to have the property there with a null value (which is what the README recommends).

**Comment by prikhi** [comment]
My bad, forgot to check the site after I pushed gh-pages.

Thanks for being on top of this @joelclermont

**Comment by JacobEvelyn** [comment]
Ah, I thought that might've been the issue but I could've sworn I saw other entries in there without the `"repositoryUrl"` field. Looks like I was mistaken though. Thanks for digging in and fixing this!

**Pull request merged**
