### PR TITLE
Add elmflux

### PR DESCRIPTION
**Pull request by yang-wei**

### CODE REVIEW

**Comment by yang-wei** [comment]
https://twitter.com/luke_dot_js/status/700563784922849280

**Comment by joelclermont** [comment]
@yang-wei Would it be possible to include an image that is 1000px wide by 800px tall. The one you've attached is only 705 x 564 so it has to stretch it. Perhaps you could slightly increase the jpg quality too, reducing the jpg artifacts? Thanks!

**Comment by yang-wei** [comment]
No problem =)

**Comment by yang-wei** [comment]
done @joelclermont

**Comment by joelclermont** [comment]
@yang-wei Looks like you changed the image to png, but did not update the json.

**Comment by yang-wei** [comment]
@joelclermont My bad. Changed.

**Pull request merged**
