### PR TITLE
Add APISnapshot

### PR DESCRIPTION
**Pull request by ritesh404**

### CODE REVIEW

**Comment by joelclermont** [comment]
Whoa, sorry this has sat out here so long. Will merge this week!

**Comment by andys8** [comment]
@joelclermont **this** weekend? ;)

**Comment by joelclermont** [comment]
Ugh, so sorry!!!! I have not forgotten, but I am very sorry to make you wait so long. I will get on this as soon as I can. :heart:

**Comment by joelclermont** [comment]
Thank you so much for your patience and the kind reminder today. All merged and deployed.

**Pull request merged**
