### PR TITLE
Add multi player rock paper scissors game

### PR DESCRIPTION
**Pull request by brianstorti**

### CODE REVIEW

**Comment by lukewestby** [comment]
Hey @brianstorti, so sorry to take so long to merge this, I'll get it up tomorrow morning at the latest

**Comment by brianstorti** [comment]
No worries :)

**Comment by lukewestby** [comment]
My coworkers and I were playing with this the other day during work 😁 very cool!

**Comment by brianstorti** [comment]
Glad to hear! :smile:

**Pull request merged**
