### PR TITLE
Keep track of current page in query string.

### PR DESCRIPTION
**Pull request by mthadley**
I noticed it was a little annoying to click on a link to a project, hit the back button, and find yourself back at the first page again.

I decided to keep it simple and just worry about parsing the query string.

Thanks!

### CODE REVIEW

**Comment by joelclermont** [comment]
Paging isn't working for me. Clicking "Older" changes the URL to index.html?page=1 but the contents don't change.

What if instead of tracking a querystring, we just had links open in a new tab?

**Comment by mthadley** [comment]
That's weird, seems fine for me:

bug

I tried rebasing my branch, but didn't see any difference.

For your suggestion, I think that could also be an improvement.

**Comment by joelclermont** [comment]
I'm just running it with elm-reactor and navigating to localhost:8000/index.html. Maybe having the index.html in the path causes the issue.

**Comment by mthadley** [comment]
Ah ok, I see the same issue with `elm-reactor`. In my testing, I was using basic web server instead.

**Comment by mthadley** [comment]
So it's basically failing to parse the URL because it is only matching `top` (which does not include `/index.html`). I can see about modifying it so that having `index.html` (or any other valid route) will still allow it to parse the query string. Shouldn't be too bad.

**Comment by joelclermont** [comment]
Thanks! Merged and deployed.

**Pull request merged**
