### PR TITLE
Convert to elm-css and add responsive layout

### PR DESCRIPTION
**Pull request by jbalboni**
I apologize in advance for the size of this. This converts all the inline styles to styles generated with elm-css. I tried not to change the current styles, unless it was necessary for the responsive changes. I think there's some cleanup there that could be another PR (things like styling classes instead of base elements in places).

Some other things of note:

- I ran the code through elm-format, which seems to have changed the indentation on every file. I can change that back if necessary.
- I couldn't get the elm-css Elm package to play nicely alongside the elm-css npm package. I get "I cannot find find module 'Css.Namespace'." when running elm-css. If I clone elm-css into the project and add it to sources, that works fine. So I've done that for now, and added elm-css to .gitignore.
- From what I can tell, elm-css doesn't support writing media queries like you would need for responsive design. I opened an [issue](https://github.com/rtfeldman/elm-css/issues/92) asking about it. For now, I created a css file with those styles.
- I tried a couple different ways of organizing styles. I had them in their own Styles directory at first, but that seemed like overkill. I also tried to include them in the existing Elm code, but that resulted in namespace conflicts with Html, and made the code ugly and confusing.
- The responsiveness is pretty basic: screen shot 2016-03-14 at 11 57 27 am

### CODE REVIEW

**Comment by lukewestby** [comment]
Awesome!

I left a comment on your elm-css issue, and I'll finish taking a look at this PR later on today or tomorrow. No worries about the PR size, it looks like most of the changes are due to new elm-format indentation width :)

**Comment by jbalboni** [comment]
@lukewestby Hey, I forgot about this! It looks like elm-css would need a change to do the responsive layout, which I might take a shot at, but I'm not sure when. Do you need anything else from me?

**Comment by lukewestby** [comment]
@jbalboni i apologize for losing focus on this as well! If you'd like to make elm-css updates please feel free, but if not I'll be happy to figure it out on my own at some point in the next couple of weeks

**Comment by jbalboni** [comment]
@lukewestby Looks like the media query thing was fixed a few weeks ago. I pushed an update set of changes, so it should be all set.

**Comment by lukewestby** [comment]
it's beautiful! thank you for the work you put in on this. it'll be published shortly and i'll be sure to give you a shoutout on twitter

**Comment by jbalboni** [comment]
Awesome! Thanks.

**Comment by lukewestby** [comment]
i had just one change after merging your pr: i separated the style definitions from the union type used for classnames. this prevents the main app from depending on all of the elm-css modules and makes the output bundle much smaller. thanks again!

**Pull request merged**
