### PR TITLE
Adds Elm Online Markdown Editor

### PR DESCRIPTION
**Pull request by 3tty0n**

### CODE REVIEW

**Comment by joelclermont** [comment]
Could you please fix the missing comma in data.json and provide an image that is exactly 1000 x 800 pixels? Thanks!

**Comment by 3tty0n** [comment]
Oh, Sorry. I'll fix ASAP.

**Comment by 3tty0n** [comment]
I have fixed it, but still conflicting...

**Comment by joelclermont** [comment]
It's probably because i merged another PR since you created yours. I can resolve it locally, no problem at all. Working on it now.

**Comment by 3tty0n** [comment]
I fetched master branch, and merged into this branch, but still conflicting.

Should I remake new PR?

**Comment by 3tty0n** [comment]
Thanks!

**Comment by joelclermont** [comment]
No need, I've already merged, resolved the conflict, and deployed. It's live! Thanks for the submission.

**Pull request merged**
