### PR TITLE
Add Elm HNPWA Project

### PR DESCRIPTION
**Pull request by rl-king**
This PR adds the Hacker News SPA I submitted for the HNPWA project.

Thanks!

### CODE REVIEW

**Comment by joelclermont** [comment]
@rl-king Could you resize the image to be 1000 x 800 pixels? Thanks!

**Comment by joelclermont** [comment]
@rl-king Also, what tool did you use to get your file size down? When I resized in Pixelmator, and ran it through ImgOptim, my file was still 80% bigger than yours, despite being 25% the size.

**Comment by joelclermont** [comment]
Thanks!

**Comment by rl-king** [comment]
@joelclermont Ah I took a screenshot with Chrome after resizing my browser to 1000x800 but apparently it saves it to the actual screen pixel size, which is higher on a hi-dpi display. I didn't check it.

I processed the image with [image alpha](https://pngmini.com) which is a pretty awesome tool for png's! You'll lose some image quality but for images like this it's great. Works well with transparency as well.

**Comment by rl-king** [comment]
Thanks for merging!

**Pull request merged**
